Main: *.java
	javac *.java
	
run: Main
	java Main
	
clean:
	rm *.class
	
package:
	javac -d ../Task2a-Type\ Checker/ Parser.java Context.java InfoTable.java TreeNode.java TokenList.java TokenNode.java;